#include <iostream>
#include <cstdlib>


void printAutoGeneratedNumbers() {
    int  number = 0;
  
    srand(time(NULL));

    for (int i = 0; i < 10; i++)
    {
        
         number = 1 + (rand() % 10000);
        
        std::cout << number << std::endl;
    }
       
    
 }

int main()
{
        printAutoGeneratedNumbers();

    return 0;
}



